# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-30 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodandacti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysecduled',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 30, 8, 54, 8, 229508)),
        ),
    ]
