# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-04 11:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodandacti', '0002_auto_20190830_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysecduled',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 4, 11, 45, 27, 82243)),
        ),
    ]
