# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-16 10:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodandacti', '0003_auto_20190904_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationlogs',
            name='HWT_of_medicine',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='medicationlogs',
            name='TMR_of_medicine',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='activitysecduled',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 16, 16, 23, 34, 225000)),
        ),
    ]
