# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-17 04:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodandacti', '0004_auto_20190916_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorTherepaticpresciption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname_t', models.CharField(max_length=300, null=True)),
                ('prescription_t', models.TextField(null=True)),
                ('patient_t', models.CharField(max_length=300, null=True)),
                ('createdDate_t', models.CharField(max_length=50, null=True)),
                ('doctor_t', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='activitysecduled',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 17, 10, 21, 4, 675000)),
        ),
    ]
