# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-17 05:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodandacti', '0005_auto_20190917_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctortherepaticpresciption',
            old_name='doctor_t',
            new_name='doctor',
        ),
        migrations.AlterField(
            model_name='activitysecduled',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 17, 10, 38, 44, 359000)),
        ),
    ]
