# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-18 04:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodandacti', '0008_auto_20190917_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysecduled',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 18, 9, 40, 31, 494000)),
        ),
    ]
