# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-30 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indian_insur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=300, null=True)),
                ('plan', models.CharField(max_length=300, null=True)),
                ('min_age', models.FloatField(null=True)),
                ('max_age', models.FloatField(null=True)),
                ('coverage', models.CharField(max_length=300, null=True)),
                ('family', models.CharField(max_length=300, null=True)),
                ('summary', models.CharField(max_length=3600, null=True)),
                ('hosp_room', models.CharField(max_length=300, null=True)),
                ('hosp_sup', models.CharField(max_length=300, null=True)),
                ('daily_cash', models.CharField(max_length=300, null=True)),
                ('pre_hosp', models.CharField(max_length=300, null=True)),
                ('posthosp', models.CharField(max_length=300, null=True)),
                ('day_care', models.CharField(max_length=300, null=True)),
                ('orgon_don', models.CharField(max_length=300, null=True)),
                ('Preventive', models.CharField(max_length=300, null=True)),
                ('Restore', models.CharField(max_length=300, null=True)),
                ('inpatient', models.CharField(max_length=300, null=True)),
                ('Ayush', models.CharField(max_length=300, null=True)),
                ('imgn', models.CharField(max_length=300, null=True)),
                ('urls', models.CharField(max_length=300, null=True)),
                ('pre_wait', models.CharField(max_length=300, null=True)),
                ('nor_wait', models.CharField(max_length=300, null=True)),
                ('max_sum', models.CharField(max_length=300, null=True)),
                ('sumassured', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
