# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-30 08:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beforelogin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100, null=True)),
                ('branch_code', models.SlugField(editable=False)),
                ('branch_address', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_name', models.CharField(max_length=100, null=True)),
                ('corporate_code', models.CharField(max_length=10, unique=True)),
                ('corporate_branch_address', models.CharField(max_length=500, null=True)),
                ('number_of_visits', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorporateHR',
            fields=[
                ('hr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('branch_code', models.CharField(max_length=100, null=True)),
                ('employee_code', models.CharField(max_length=100, null=True)),
                ('Designation', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100, null=True)),
                ('organization_id', models.CharField(max_length=10, null=True, unique=True)),
                ('organization_address', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PHID', models.SlugField(editable=False)),
                ('phillhealth_id', models.TextField(null=True)),
                ('branch_code', models.CharField(max_length=100, null=True)),
                ('employee_id', models.TextField(null=True)),
                ('patient_type', models.CharField(max_length=100, null=True)),
                ('corporate_code', models.CharField(max_length=100, null=True)),
                ('pat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('patient_code', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(blank=True, max_length=300, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('reset_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Qualification', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('branch_code', models.CharField(max_length=100, null=True)),
                ('speciality', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('Licence_number', models.CharField(max_length=100)),
                ('pro', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.IntegerField(null=True)),
                ('istreated', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beforelogin.Usertypes'),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctorid',
            field=models.ManyToManyField(blank=True, null=True, to='usermanagement.Staff'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pro',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.Profile'),
        ),
        migrations.AddField(
            model_name='corporatehr',
            name='pro',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.Profile'),
        ),
        migrations.AddField(
            model_name='branch',
            name='organaisation_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.Distributor'),
        ),
    ]
