# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-04 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_auto_20190830_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatehr',
            name='branch_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
